-- Mental Health Sentiment Analysis System - Database Setup Script
-- -----------------------------------------------------------------------------------------------------------
-- Create the database and select it
CREATE DATABASE IF NOT EXISTS mental_health_db;
USE mental_health_db;
-- -----------------------------------------------------------------------------------------------------------
Create stop_words table CREATE TABLE IF NOT EXISTS stop_words(
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(64) NOT NULL UNIQUE,
    INDEX idx_word(word)
);
INSERT INTO stop_words(word)
VALUES -- Articles
    ('a'),
    ('an'),
    ('the'),
    -- Conjunctions (Coordinating)
    ('and'),
    ('or'),
    ('but'),
    ('yet'),
    ('nor'),
    ('so'),
    ('for'),
    -- Conjunctions (Subordinating)
    ('because'),
    ('although'),
    ('though'),
    ('if'),
    ('unless'),
    ('while'),
    ('when'),
    ('whenever'),
    ('where'),
    ('wherever'),
    ('since'),
    ('until'),
    ('whether'),
    ('before'),
    ('after'),
    ('as'),
    ('whereas'),
    ('lest'),
    ('provided'),
    ('that'),
    ('once'),
    ('above'),
    ('below'),
    ('between'),
    ('under'),
    ('again'),
    ('further'),
    ('then'),
    ('once'),
    -- Pronouns
    ('i'),
    ('you'),
    ('he'),
    ('she'),
    ('it'),
    ('we'),
    ('they'),
    ('me'),
    ('him'),
    ('her'),
    ('us'),
    ('them'),
    ('my'),
    ('your'),
    ('his'),
    ('her'),
    ('its'),
    ('our'),
    ('their'),
    ('mine'),
    ('yours'),
    ('hers'),
    ('ours'),
    ('theirs'),
    ('this'),
    ('that'),
    ('these'),
    ('those'),
    -- Auxiliary verbs
    ('am'),
    ('is'),
    ('are'),
    ('was'),
    ('were'),
    ('be'),
    ('been'),
    ('being'),
    ('have'),
    ('has'),
    ('had'),
    ('do'),
    ('does'),
    ('did'),
    ('will'),
    ('would'),
    ('could'),
    ('should'),
    ('may'),
    ('might'),
    ('must'),
    ('can'),
    -- Other common words
    ('just'),
    ('only'),
    ('not'),
    ('no'),
    ('than'),
    ('too'),
    ('very'),
    ('each'),
    ('such'),
    ('which'),
    ('who'),
    ('what'),
    ('why'),
    ('how'),
    ('all'),
    ('some'),
    ('any'),
    ('few'),
    ('many'),
    ('most'),
    ('other'),
    ('same'),
    ('more'),
    ('less'),
    ('down'),
    ('out'),
    ('off'),
    ('over'),
    ('own'),
    ('both'),
    ('here'),
    ('there'),
    ('now'),
    ('then'),
    ('however'),
    ('therefore'),
    ('thus'),
    ('hence'),
    ('also'),
    ('else') ON DUPLICATE KEY
UPDATE word =
VALUES(word);
-- ---------------------------------------------------------------------------------------------------------
-- Creating table for storing emotional words and their Naive Bayes score for being Depressed and Non-Depressed
CREATE TABLE IF NOT EXISTS emotional_words (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(64) NOT NULL UNIQUE,
    happy_count INT NOT NULL DEFAULT 1,
    happy_score FLOAT NOT NULL DEFAULT 0.001,
    sad_count INT NOT NULL DEFAULT 1,
    sad_score FLOAT NOT NULL DEFAULT 0.001,
    confused_count INT NOT NULL DEFAULT 1,
    confused_score FLOAT NOT NULL DEFAULT 0.001,
    angry_count INT NOT NULL DEFAULT 1,
    angry_score FLOAT NOT NULL DEFAULT 0.001,
    fear_count INT NOT NULL DEFAULT 1,
    fear_score FLOAT NOT NULL DEFAULT 0.001,
    disgust_count INT NOT NULL DEFAULT 1,
    disgust_score FLOAT NOT NULL DEFAULT 0.001,
    neutral_count INT NOT NULL DEFAULT 1,
    neutral_score FLOAT NOT NULL DEFAULT 0.001,
    INDEX idx_word(word)
);
-- ------------------------------------------------------------------------------------------------------------
-- Adding the emotional words
INSERT INTO emotional_words (word) -- Daily Use Words
VALUES ('upset'),
    ('down'),
    ('hurt'),
    ('heartbroken'),
    ('broken'),
    ('lost'),
    ('worried'),
    ('nervous'),
    ('afraid'),
    ('terrified'),
    ('exhausted'),
    ('weak'),
    ('angry'),
    ('mad'),
    ('annoyed'),
    ('upbeat'),
    ('cheerful'),
    ('delighted'),
    ('thrilled'),
    ('excited'),
    ('motivated'),
    ('encouraged'),
    ('inspired'),
    ('secure'),
    ('comfortable'),
    ('safe'),
    ('loved'),
    ('caring'),
    ('friendly'),
    ('hope'),
    ('sadness'),
    ('happiness'),
    ('joy'),
    ('sorrow'),
    ('grief'),
    ('pain'),
    ('suffering'),
    ('comfort'),
    ('trust'),
    ('doubt'),
    ('worry'),
    ('fear'),
    ('anger'),
    ('rage'),
    ('calmness'),
    ('loneliness'),
    ('stress'),
    ('anxiety'),
    ('depression'),
    ('confidence'),
    ('motivation'),
    ('discouraged'),
    ('rejected'),
    ('abandoned'),
    ('isolated'),
    ('defeated'),
    ('troubled'),
    ('disturbed'),
    ('restless'),
    ('uneasy'),
    ('shattered'),
    ('crushed'),
    ('healed'),
    ('supported'),
    ('accepted'),
    ('valued'),
    ('energized'),
    ('refreshed'),
    ('hopefulness'),
    ('peace'),
    ('satisfaction'),
    ('fulfillment'),
    ('connected'),
    ('encouraging'),
    ('empathetic'),
    ('understood'),
    ('securely'),
    ('lively'),
    ('pleasant'),
    ('bright'),
    ('uplifted'),
    ('cheered') -- Gen Z/Internet Slang
    ('ick'),
    ('cringe'),
    ('cringey'),
    ('fomo'),
    ('obsessed'),
    ('downbad'),
    ('simping'),
    ('unhinged'),
    ('spiraling'),
    ('wreckingme') -- High Vocabulary Words
    ('anguish'),
    ('desolation'),
    ('forlorn'),
    ('morose'),
    ('lachrymose'),
    ('woebegone'),
    ('disconsolate'),
    ('crestfallen'),
    ('dispirited'),
    ('inconsolable'),
    ('tormented'),
    ('bereaved'),
    ('alienated'),
    ('estranged'),
    ('disillusioned'),
    ('disenchanted'),
    ('despondency'),
    ('ennui'),
    ('listless'),
    ('morbid'),
    ('ruminative'),
    ('catatonic'),
    ('apathetic'),
    ('vacant'),
    ('forfeit'),
    ('disquiet'),
    ('perturbed'),
    ('distraught'),
    ('harrowed'),
    ('anguished'),
    ('afflicted'),
    ('oppressed'),
    ('burdened'),
    ('melancholic'),
    ('lugubrious'),
    ('somber'),
    ('brooding'),
    ('woeful'),
    ('plaintive'),
    ('miserly'),
    ('sullen'),
    ('taciturn'),
    ('reticent'),
    ('withdrawn'),
    ('introverted'),
    ('repressed'),
    ('suppressed'),
    ('despairing'),
    ('lamenting'),
    ('aggrieved'),
    ('pensive'),
    ('rueful'),
    ('forbearing'),
    ('reclusive'),
    ('desperate'),
    ('forsaken'),
    ('abject'),
    ('subdued'),
    ('debilitated'),
    ('enervated'),
    ('lethargic'),
    ('disoriented'),
    ('bewildered'),
    ('perplexed'),
    ('appalled'),
    ('aghast'),
    ('mortified'),
    ('horrified'),
    ('shocked'),
    ('dismayed'),
    ('distressed'),
    ('traumatized'),
    ('demoralized'),
    ('dejected'),
    ('soulful'),
    ('introspective'),
    ('yearning'),
    ('wistfulness'),
    ('rumination'),
    ('despondence'),
    ('lamentation'),
    ('desolationist'),
    ('alienation'),
    ('solitude'),
    ('vacillation'),
    ('trepidation'),
    ('foreboding'),
    ('apprehension'),
    ('consternation'),
    ('discomfiture'),
    ('perturbation'),
    ('melancholia'),
    ('anhedonia'),
    ('dysphoria'),
    ('euphoria'),
    ('equanimity'),
    ('serendipity'),
    ('beatitude'),
    ('contentment'),
    ('benevolence'),
    ('compunction'),
    ('contrition'),
    ('reconciliation') -- Clinical/Mental Health Terms
    ('anhedonic'),
    ('dysphoric'),
    ('ruminating'),
    ('rumination'),
    ('hopelessness'),
    ('worthlessness'),
    ('burnedout'),
    ('burntout'),
    ('overthinking'),
    ('helplessness'),
    ('panic'),
    ('distress'),
    ('traumatized'),
    ('trauma'),
    ('grieving'),
    ('mourning'),
    ('disassociation'),
    ('derealization'),
    ('numbness'),
    ('avoidance'),
    ('isolation'),
    ('emptiness'),
    ('desperation') --more words
    -- Happy / Positive
    ('happy'),
    ('joyful'),
    ('glad'),
    ('pleased'),
    ('blissful'),
    ('elated'),
    ('ecstatic'),
    ('jubilant'),
    ('radiant'),
    ('grateful'),
    ('thankful'),
    ('optimistic'),
    ('hopeful'),
    ('relieved'),
    ('proud'),
    ('accomplished'),
    ('successful'),
    ('enthusiastic'),
    ('passionate'),
    ('thriving'),
    ('cheery'),
    ('playful'),
    ('amused'),
    ('satisfied'),
    ('fulfilled'),
    ('uplifting'),
    ('positive'),
    ('affectionate'),
    ('adored'),
    ('cherished'),
    ('blessed'),
    ('fortunate'),
    ('merry'),
    ('gleeful'),
    ('vibrant'),
    ('sunny'),
    ('spirited'),
    ('exuberant'),
    ('overjoyed'),
    ('reassured'),
    ('validated'),
    ('celebratory'),
    ('triumphant'),
    ('glowing'),
    ('vibing'),
    ('hyped'),
    ('pumped'),
    ('slaying'),
    ('winning'),
    -- Sad / Depression
    ('sorrowful'),
    ('downcast'),
    ('blue'),
    ('gloomy'),
    ('mournful'),
    ('griefstricken'),
    ('brokenhearted'),
    ('tearful'),
    ('weeping'),
    ('wounded'),
    ('deflated'),
    ('neglected'),
    ('unwanted'),
    ('unloved'),
    ('bereft'),
    ('disheartened'),
    ('downhearted'),
    ('drained'),
    ('wrecked'),
    ('deadinside'),
    ('low'),
    ('powerless'),
    ('forgotten'),
    ('heartache'),
    ('heartached'),
    -- Anger
    ('furious'),
    ('enraged'),
    ('irritated'),
    ('frustrated'),
    ('outraged'),
    ('resentful'),
    ('bitter'),
    ('hostile'),
    ('aggressive'),
    ('offended'),
    ('provoked'),
    ('agitated'),
    ('infuriated'),
    ('fuming'),
    ('livid'),
    ('irate'),
    ('wrathful'),
    ('seething'),
    ('vexed'),
    ('exasperated'),
    ('impatient'),
    ('heated'),
    ('cross'),
    ('hateful'),
    ('spiteful'),
    ('vengeful'),
    ('vindictive'),
    ('indignant'),
    ('antagonistic'),
    ('argumentative'),
    ('combative'),
    ('rebellious'),
    ('explosive'),
    ('volatile'),
    ('temperamental'),
    ('grumpy'),
    ('snappy'),
    ('raging'),
    ('unforgiving'),
    ('resentment'),
    ('wrath'),
    ('triggered'),
    ('salty'),
    ('pressed'),
    -- Fear / Anxiety
    ('fearful'),
    ('scared'),
    ('frightened'),
    ('panicked'),
    ('alarmed'),
    ('petrified'),
    ('paranoid'),
    ('insecure'),
    ('vulnerable'),
    ('threatened'),
    ('intimidated'),
    ('startled'),
    ('shaken'),
    ('timid'),
    ('cowardly'),
    ('hesitant'),
    ('tense'),
    ('jittery'),
    ('spooked'),
    ('haunted'),
    ('concerned'),
    ('terror'),
    ('hysteria'),
    ('suspicious'),
    ('cautious'),
    ('wary'),
    ('doubtful'),
    ('fretful'),
    ('fearsome'),
    ('frantic'),
    ('panicking'),
    -- Disgust
    ('disgusted'),
    ('repulsed'),
    ('revolted'),
    ('grossed'),
    ('nauseated'),
    ('sickened'),
    ('abhorrent'),
    ('detested'),
    ('loathing'),
    ('repelled'),
    ('disapproving'),
    ('contemptuous'),
    ('scornful'),
    ('revulsed'),
    ('nasty'),
    ('filthy'),
    ('dirty'),
    ('vile'),
    ('foul'),
    ('offput'),
    ('offputting'),
    ('unpleasant'),
    ('objectionable'),
    ('offensive'),
    ('distasteful'),
    ('hideous'),
    ('grotesque'),
    ('abhorred'),
    ('despised'),
    ('loathed'),
    ('cringing'),
    ('icky'),
    ('ew'),
    ('yuck'),
    ('disdainful'),
    ('contempt'),
    ('aversion'),
    ('revulsion'),
    -- Confusion
    ('confused'),
    ('unsure'),
    ('conflicted'),
    ('indecisive'),
    ('questioning'),
    ('unclear'),
    ('muddled'),
    ('baffled'),
    ('stumped'),
    ('misguided'),
    ('ambivalent'),
    ('torn'),
    ('wondering'),
    ('curious'),
    ('skeptical'),
    ('dubious'),
    ('mixedup'),
    ('foggy'),
    ('blank'),
    ('clueless'),
    ('misunderstood'),
    ('distracted'),
    ('scattered'),
    ('confounded'),
    ('flustered'),
    ('rattled'),
    ('disconnected'),
    ('wavering'),
    ('unsettled'),
    ('undecided'),
    ('confusion') ON DUPLICATE KEY
UPDATE word =
VALUES(word);
------------------------------------------------------------------------------------------------------------
-- Creating a table for storing probability of a message being one of these emotions.
CREATE TABLE IF NOT EXISTS message_emotion_probabilities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    emotion VARCHAR(64) NOT NULL UNIQUE,
    probability DOUBLE NOT NULL DEFAULT 0.001,
    count INT NOT NULL DEFAULT 1,
    INDEX idx_emotion(emotion)
);
INSERT INTO message_emotion_probabilities (emotion)
VALUES ('happy'),
    ('sad'),
    ('confused'),
    ('angry'),
    ('fear'),
    ('disgust'),
    ('neutral') ON DUPLICATE KEY
UPDATE emotion =
VALUES(emotion);