-- Mental Health Sentiment Analysis System - Database Setup Script
-- -----------------------------------------------------------------------------------------------------------
-- Create the database and select it
CREATE DATABASE IF NOT EXISTS mental_health_db;
USE mental_health_db;
-- -----------------------------------------------------------------------------------------------------------
-- Create stop_words table
-- Columns:
--   - id
--   - word(unique)
-- CREATE TABLE IF NOT EXISTS stop_words(
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     word VARCHAR(100) NOT NULL UNIQUE,
--     INDEX idx_word(word)
-- );
-- INSERT INTO stop_words(word)
-- VALUES -- Articles
--     ('a'),
--     ('an'),
--     ('the'),
--     -- Conjunctions (Coordinating)
--     ('and'),
--     ('or'),
--     ('but'),
--     ('yet'),
--     ('nor'),
--     ('so'),
--     ('for'),
--     -- Conjunctions (Subordinating)
--     ('because'),
--     ('although'),
--     ('though'),
--     ('if'),
--     ('unless'),
--     ('while'),
--     ('when'),
--     ('whenever'),
--     ('where'),
--     ('wherever'),
--     ('since'),
--     ('until'),
--     ('whether'),
--     ('before'),
--     ('after'),
--     ('as'),
--     ('whereas'),
--     ('lest'),
--     ('provided'),
--     ('that'),
--     ('once'),
--     ('above'),
--     ('below'),
--     ('between'),
--     ('under'),
--     ('again'),
--     ('further'),
--     ('then'),
--     ('once'),
--     -- Pronouns
--     ('i'),
--     ('you'),
--     ('he'),
--     ('she'),
--     ('it'),
--     ('we'),
--     ('they'),
--     ('me'),
--     ('him'),
--     ('her'),
--     ('us'),
--     ('them'),
--     ('my'),
--     ('your'),
--     ('his'),
--     ('her'),
--     ('its'),
--     ('our'),
--     ('their'),
--     ('mine'),
--     ('yours'),
--     ('hers'),
--     ('ours'),
--     ('theirs'),
--     ('this'),
--     ('that'),
--     ('these'),
--     ('those'),
--     -- Auxiliary verbs
--     ('am'),
--     ('is'),
--     ('are'),
--     ('was'),
--     ('were'),
--     ('be'),
--     ('been'),
--     ('being'),
--     ('have'),
--     ('has'),
--     ('had'),
--     ('do'),
--     ('does'),
--     ('did'),
--     ('will'),
--     ('would'),
--     ('could'),
--     ('should'),
--     ('may'),
--     ('might'),
--     ('must'),
--     ('can'),
--     -- Other common words
--     ('just'),
--     ('only'),
--     ('not'),
--     ('no'),
--     ('than'),
--     ('too'),
--     ('very'),
--     ('each'),
--     ('such'),
--     ('which'),
--     ('who'),
--     ('what'),
--     ('why'),
--     ('how'),
--     ('all'),
--     ('some'),
--     ('any'),
--     ('few'),
--     ('many'),
--     ('most'),
--     ('other'),
--     ('same'),
--     ('more'),
--     ('less'),
--     ('down'),
--     ('out'),
--     ('off'),
--     ('over'),
--     ('own'),
--     ('both'),
--     ('here'),
--     ('there'),
--     ('now'),
--     ('then'),
--     ('however'),
--     ('therefore'),
--     ('thus'),
--     ('hence'),
--     ('also'),
--     ('else') ON DUPLICATE KEY
-- UPDATE word =
-- VALUES(word);
-- ---------------------------------------------------------------------------------------------------------


-- Creating table for storing emotional words and their Naive Bayes score for being Depressed and Non-Depressed
CREATE TABLE IF NOT EXISTS emotional_words (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(255) NOT NULL UNIQUE,
    depressed_score FLOAT NOT NULL DEFAULT 0.001,
    non_depressed_score FLOAT NOT NULL DEFAULT 0.001,
    INDEX idx_word(word)
);

-- ------------------------------------------------------------------------------------------------------------

-- Adding the emotional words
INSERT INTO emotional_words (word) VALUES
    ('sad'),
    ('depressed'),
    ('unhappy'),
    ('miserable'),
    ('hopeless'),
    ('lonely'),
    ('worthless'),
    ('guilty'),
    ('tired'),
    ('anxious'),
    ('stressed'),
    ('overwhelmed'),
    ('numb'),
    ('empty'),
    ('crying'),
    ('suicidal'),
    ('fatigued'),
    ('insomnia'),
    ('irritable'),
    ('withdrawn'),
    ('apathy'),
    ('helpless'),
    ('despair'),
    ('self-harm'),
    ('negative'),
    ('pessimistic'),
    ('gloomy'),
    ('melancholy'),
    ('dejection'),
    ('despondent'),
    ('disheartened'),
    ('scared'),
    ('fearful'),
    ('panicked'),
    ('agitated'),
    ('frustrated'),
    ('resentful'),
    ('ashamed'),
    ('embarrassed'),
    ('confused'),
    ('hopeful'),
    ('relieved'),
    ('calm'),
    ('peaceful'),
    ('content'),
    ('happy'),
    ('joyful'),
    ('grateful'),
    ('curious'),
    ('nostalgic'),
    ('regretful'),
    ('remorseful'),
    ('betrayed'),
    ('enraged'),
    ('furious'),
    ('jealous'),
    ('envious'),
    ('serene'),
    ('eager'),
    ('relaxed'),
    ('elated'),
    ('optimistic'),
    ('disappointed'),
    ('dismayed'),
    ('apprehensive'),
    ('uneasy'),
    ('tense'),
    ('startled'),
    ('suspicious'),
    ('wistful'),
    ('mournful'),
    ('vulnerable'),
    ('sensitive'),
    ('dazed'),
    ('carefree'),
    ('proud'),
    ('sympathetic'),
    ('compassionate'),
    ('resigned'),
    ('detached'),
    ('insecure'),
    ('resilient'),
    -- GenZ words
    ('mood'),
    ('shook'),
    ('salty'),
    ('stoked'),
    ('vibey'),
    ('drained'),
    ('burnout'),
    ('ghosted'),
    ('extra'),
    ('goals'),
    ('lowkey'),
    ('highkey'),
    ('thirsty'),
    ('bussin'),
    ('woke'),
    ('lit'),
    ('stan'),
    ('sus'),
    ('hyped'),
    ('vibin'),
    ('blessed'),
    ('bummed'),
    ('rattled'),
    ('shooketh'),
    ('snatched'),
    ('yikes') ON DUPLICATE KEY
UPDATE word = VALUES(word);